### ISSUE TITLE
Can't play yt videos

### ISSUE THREAD

**Issue by bitRocky** [walkero-gr/aiostreams#3]
If I try to play a yt video, I get this error msg:
---
c:python2.5   youtube.py -u "https://www.youtube.com/watch?v=UrGS_6_HglU"
aiostreams v1.6.2 (2020-07-27) - Developed by George Sokianos

Traceback (most recent call last):
  File "youtube.py", line 385, in <module>
    main(sys.argv[1:])
  File "youtube.py", line 327, in main
    print response['playabilityStatus']['reason']
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 16: ordinal not in range(128)
---
I'm using MorphOS.

**Comment by walkero-gr** [comment]
Thank you for your message. This video seems unplayable outside of youtube. At least that what the YouTube API returns. Now, the error messages you see it seems that the reason message that YT return has a character that is unicode and is not translated right in MorphOS. I will try to figure out what the problem is and fix it.

Unfortunately, this script currently doesn't support all the videos on YouTube, especially the locked and ciphered ones. It mostly works great with live streams.

**Comment by bitRocky** [comment]
Thanks for the quick reply!Am 01.08.2020 19:22 schrieb George Sokianos <notifications@github.com>:
Thank you for your message. This video seems unplayable outside of youtube. At least that what the YouTube API returns. Now, the error messages you see it seems that the reason message that YT return has a character that is unicode and is not translated right in MorphOS. I will try to figure out what the problem is and fix it.
Unfortunately, this script currently doesn't support all the videos on YouTube, especially the locked and ciphered ones. It mostly works great with live streams.
